# Repository Architecture

Requested task: Create a new file named `format_date_test.js` inside the `tests/unit` directory with the following content:

```javascript
test('should format dates correctly', () => {
    expect(formatDate(new Date())).toBe('2024-11-15'); // Example date
});
```
Ensure no other files are modified and that this test is added to `.gitignore` if necessary.

## Top-level Structure
- .env.example
- apps/
  - client/
  - localbuddy/
  - remotebuddy/
  - server/
  - source_control_manager/
  - workerpals/
- bun.lock
- LICENSE
- package.json
- packages/
  - protocol/
  - shared/
- prompts/
  - localbuddy/
  - remotebuddy/
  - shared/
  - workerpals/
- README.md
- scripts/
  - smoke-test.ts
  - start-client.ts
  - start.ts
- tests/
  - localbuddy.local-readonly.test.ts
  - localbuddy.request-status.test.ts
  - protocol.integration.ts
  - remotebuddy.brain-planner.test.ts
  - server.jobs.stale-recovery.test.ts
  - server.requests-queue.test.ts
  - workerpals.shell-manager.manual.ts
  - workerpals.shell-manager.test.ts
  - workerpals.task-execute-schema.test.ts
  - workerpals.timeout-policy.test.ts
- tmp_debug_assistant.js

## README Excerpt
# Push Pals

Multi-device, always-on, multi-agent coding with clear orchestration and auditability.

## Overview

Push Pals runs a small software "team" around your repository:

- `apps/client`: chat UI (Expo web/mobile)
- `apps/server`: event hub + persistence + queues (SQLite)
- `apps/localbuddy`: `LocalBuddy` HTTP ingress + deterministic local routing
- `apps/remotebuddy`: `RemoteBuddy` strict planner + orchestrator
- `apps/workerpals`: `WorkerPals` strict `task.execute` runners (deterministic/OpenHands lanes)
- `apps/source_control_manager`: `SourceControlManager` merge/push daemon

## Current Architecture

## Architecture Diagram

### End-to-end system view

```mermaid
flowchart LR
  User[User] --> Client[apps/client\nExpo UI]
  Client -->|POST /message| LocalBuddy[apps/localbuddy\nIngress + Prompt Enrichment]
  LocalBuddy -->|POST /requests/enqueue| Server[(apps/server\nEvents + Queues + SQLite)]
  Server -->|SSE / WS session events| Client

  Server -->|POST /requests/claim| RemoteBuddy[apps/remotebuddy\nOrchestrator + Scheduler]
  RemoteBuddy -->|POST /jobs/enqueue| Server
  Server -->|POST /jobs/claim| WorkerPals[apps/workerpals\nExecution Daemons]

  WorkerPals -->|job_log / job_completed / job_failed| Server
  WorkerPals -->|POST /completions/enqueue| Server

  Server -->|POST /completions/claim| SCM[apps/source_control_manager\nMerge + Push + PR]
  SCM -->|assistant/status events| Server
  Server -->|SSE / WS session events| Client

  subgraph Git[Git + Branch Flow]
    WorkerBranch[agent/<worker>/<job>] --> Integration[main_agents]
    Integration --> Main[main]
  end

  WorkerPals -->|commit refs| WorkerBranch
  SCM -->|cherry-pick/merge + push| Integration
```

### Communication model (event-driven)

```mermaid
sequenceDiagram
  participant U as User
  participant C as Client
  participant L as LocalBuddy
  participant S as Server
  participant R as RemoteBuddy
  participant W as WorkerPals
  participant M as SourceControlManager

  U->>C: Send request
  C->>L: POST /message
  L->>S: session message + status events
  L->>S: POST /requests/enqueue
  R->>S: POST /requests/claim
  R->>S: task/job events + POST /jobs/enqueue
  W->>S: POST /jobs/claim
  W->>S: job_log + job_completed/job_failed events
  W->>S: POST /completions/enqueue
  M->>S: POST /completions/claim
  M->>S: merge/push outcome events
  S-->>C: SSE/WS stream (live timeline)
```

#

## Recent Worker Job Context
- warmup.execute [completed]: Startup warmup completed (no-op, no commit).

Generated by worker task.execute (lane=deterministic) from repository state.
