/**
 * Shared utilities package
 */

export {
  detectRepoRoot,
  findGitRepoRoot,
  getRepoContext,
  resolveGitMetadataDir,
  resolveGitStateFilePath,
} from "./repo.js";
export {
  normalizeRepositoryOriginRemote,
  resolveRepositoryIdentity,
  type RepositoryIdentity,
  type RepositoryIdentityGitResult,
  type RepositoryIdentitySource,
  type ResolveRepositoryIdentityOptions,
} from "./repository_identity.js";
export {
  RepositorySnapshotError,
  resolveRepositorySnapshot,
  type RepositorySnapshot,
  type RepositorySnapshotErrorCode,
  type RepositorySnapshotFileHandle,
  type RepositorySnapshotFileSystem,
  type RepositorySnapshotGitResult,
  type RepositorySnapshotGitRunner,
  type ResolveRepositorySnapshotOptions,
} from "./repository_snapshot.js";
export {
  InMemoryMemoryStore,
  appendMemoryReinforcementObservation,
  assertMemoryReinforcementObservationCompatible,
  assertMemoryReinforcementOutcome,
  createMemoryReinforcementObservation,
  MEMORY_HTTP_AUTHORITY_HEADER,
  MEMORY_HTTP_CALLER_HEADER,
  MEMORY_LIMITS,
  MEMORY_REINFORCEMENT_OUTCOMES,
  MAX_MEMORY_REINFORCEMENT_OBSERVATIONS,
  MemoryConflictError,
  MemoryHttpClient,
  MemoryHttpError,
  MemoryStoreClosedError,
  MemoryValidationError,
  isMemoryReinforcementOutcome,
  memoryRecordRankingQuality,
  resolveMemoryReinforcement,
  REPOSITORY_AGENT_MEMORY_NAMESPACES,
  serializedMemoryRecordChars,
  type MemoryAddress,
  type MemoryEvidence,
  type MemoryGetOptions,
  type MemoryHttpClientOptions,
  type MemoryHttpAuthority,
  type MemoryHttpCallerService,
  type MemoryInvalidateSelector,
  type MemoryJsonPrimitive,
  type MemoryJsonValue,
  type MemoryProvenance,
  type MemoryPruneOptions,
  type MemoryPutInput,
  type MemoryPutOptions,
  type MemoryRecord,
  type MemoryReinforcementEffect,
  type MemoryReinforcementObservation,
  type MemoryReinforcementOutcome,
  type MemoryReinforceInput,
  type MemoryScope,
  type MemorySearchQuery,
  type MemoryStatus,
  type MemoryStore,
  type MemoryValidationErrorCode,
} from "./memory.js";
export * from "./repository_agent.js";
export { CommunicationManager, type CommunicationManagerOptions } from "./communication.js";
export {
  DEFAULT_MAX_BUFFERED_RESPONSE_BYTES,
  fetchBufferedWithHardDeadline,
  fetchWithHardDeadline,
  type FetchBufferedWithHardDeadlineOptions,
  type FetchLike,
  type FetchWithHardDeadlineOptions,
} from "./bounded_fetch.js";
export {
  buildWindowsDescendantSweepArgv,
  buildWindowsProcessTreeTerminationArgv,
  runBoundedProcess,
  terminateProcessTree,
  type BoundedProcessResult,
  type BoundedProcessSpawner,
  type BoundedSubprocess,
} from "./bounded_process.js";
export {
  SCM_REPAIR_AUTHORITY_HEADER,
  SCM_REPAIR_AUTHORITY_SECRET_ENV,
  copyEnvWithoutScmRepairAuthoritySecret,
  createScmRepairAuthorityProof,
  resolveScmRepairAuthoritySecret,
  scrubScmRepairAuthoritySecretFromEnv,
  takeScmRepairAuthoritySecretFromEnv,
  verifyScmRepairAuthorityProof,
  type ScmRepairAuthorityVerification,
} from "./scm_repair_authority.js";
export { loadPromptTemplate, loadRepoDocText } from "./prompts.js";
export {
  evaluateClientRuntimePreflight,
  formatClientRuntimePreflightLines,
  type ClientPreflightCopyCommands,
  type ClientPreflightIssue,
  type ClientRuntimePreflightResult,
} from "./client_preflight.js";
export {
  extractVisionKeyItems,
  normalizeVisionSectionRef,
  normalizeVisionSectionRefs,
  parseVisionDoc,
  validateVisionDocStructure,
  type ParsedVisionDoc,
  type VisionDocValidation,
  type VisionKeyItems,
  type VisionSection,
} from "./vision.js";
export {
  inferGitBackendFromRemote,
  parseGitHubRepo,
  parseGitRemoteHost,
  resolveGitTokenForRemote,
  sanitizeGitRemoteUrl,
  toGitHubRepoWebUrl,
  type CommandCaptureResult,
  type GitBackendId,
  type GitHubRepoRef,
  type GitTokenResolution,
  type GitTokenSource,
  type ResolveGitTokenOptions,
} from "./git_backend.js";
export {
  assertSupportedSourceControlProvider,
  buildGitCommitArgs,
  explicitSourceControlCommitIdentityFromEnv,
  normalizeSourceControlProvider,
  resolveSourceControlProvider,
  sanitizeSourceControlIdentityField,
  type SourceControlCommitIdentity,
  type SourceControlCommitIdentitySource,
  type SourceControlProvider,
} from "./source_control_api.js";
export {
  DEFAULT_TOOL_REGISTRY,
  TOOL_RUN_TAIL_CHARS,
  classifyToolFailure,
  createToolRunRecordFromFailure,
  inferToolNameFromFailureText,
  isWorkerOwnedRuntimeStackFrame,
  normalizeToolName,
  redactToolText,
  resolveToolKind,
  truncateToolText,
  type ToolAdapter,
  type ToolEffect,
  type ToolFailureClass,
  type ToolFailureClassification,
  type ToolFailureInput,
  type ToolKind,
  type ToolRegistry,
  type ToolRunRecord,
} from "./tooling.js";
export {
  buildToolchainPlan,
  formatToolRequirement,
  inferToolRequirementsForValidationCommand,
  requirementsForValidationCommand,
  tokenizeToolchainCommand,
  type BuildToolchainPlanOptions,
  type ToolRequirement,
  type ToolchainEnvironmentSource,
  type ToolchainPlan,
} from "./toolchain.js";
export {
  inferRepositoryValidationSteps,
  mergeRepositoryValidationSteps,
  type InferRepositoryValidationStepsOptions,
  type MergeRepositoryValidationStepsOptions,
  type RepositoryValidationEcosystem,
} from "./repo_validation.js";
export {
  MAX_TRUSTED_VALIDATION_COMMANDS,
  MAX_TRUSTED_VALIDATION_COMMAND_LENGTH,
  extractTrustedValidationFailureEvidence,
  normalizeTrustedValidationFingerprintLine,
  normalizeTrustedValidationCommands,
  tokenizeTrustedValidationCommand,
  truncateTrustedValidationOutput,
  type TrustedValidationExecutionResult,
  type TrustedValidationFailureEvidence,
  type TrustedValidationPhase,
  type TrustedValidationReport,
  type TrustedValidationCommandsResult,
} from "./trusted_validation.js";
export {
  appendValidationRepairPublicationLease,
  parseValidationRepairPublicationLease,
  validateValidationRepairPublicationLease,
  validationRepairPublicationLeaseFromJobParams,
  type ValidationRepairPublicationLease,
} from "./validation_repair_lease.js";
export {
  MINIMUM_SUPPORTED_BUN_VERSION,
  isSupportedBunVersion,
  parseRuntimeVersion,
  runtimeVersionAtLeast,
  type RuntimeVersionTuple,
} from "./runtime_version.js";
export {
  DEFAULT_WORKERPALS_EXECUTOR,
  invalidatePushPalsConfigCache,
  loadPushPalsConfig,
  sanitizePushPalsConfigForLogging,
  type PushPalsConfig,
  type PushPalsLlmConfig,
  type PushPalsLmStudioConfig,
} from "./config.js";
export {
  buildLocalCorsHeaders,
  isLoopbackOrigin,
  isLoopbackHost,
  normalizeLoopbackHost,
  normalizeLoopbackHttpUrl,
  resolveLocalServerConnection,
} from "./local_network.js";
export {
  isHeartbeatStatusSessionEvent,
  shouldDisplayInteractiveSessionEvent,
} from "./session_event_visibility.js";
export {
  DEFAULT_LOCALBUDDY_PORT,
  computeLocalBuddyRestartBackoffMs,
  loadLocalBuddyRuntimeSnapshotFromFiles,
  parseLocalBuddyRuntimeSnapshot,
  resolveLocalBuddyRuntimeAction,
  resolveLocalBuddyStartGate,
  type LocalBuddyRuntimeAction,
  type LocalBuddyRuntimeSnapshot,
  type LocalBuddyStartGateReason,
} from "./localbuddy_runtime.js";
export {
  classifyGlobBreadth,
  componentRootPrefix,
  containsGlobMeta,
  deriveAutonomyComponentArea,
  globBreadthScore,
  literalPrefix,
  makePatternKey,
  matchesGlob,
  normalizeAutonomyComponentArea,
  normalizePenalties,
  normalizeRepoRelativePath,
  normalizeTargetPath,
  normalizeWriteGlob,
  penaltyTotal,
  validateScopeInvariants,
  type AutonomyComponentArea,
  type AutonomyGlobBreadth,
  type AutonomyObjectiveType,
  type AutonomyPenalty,
  type AutonomyPenaltyKind,
  type AutonomyRiskLevel,
  type ScopeValidationResult,
} from "./autonomy_policy.js";
